const dummyMyArticleList = [
  {
    articleId: '1',
    image: 'image',
    category: {
      cid: '1325153',
      oneDepth: '',
      twoDepth: '',
      threeDepth: '',
      fourDepth: '',
      fiveDepth: '',
    },
    title: '테스트용',
    tprice: 150000,
  },
  {
    articleId: '2',
    image: 'image',
    category: {
      cid: '1325153',
      oneDepth: '',
      twoDepth: '',
      threeDepth: '',
      fourDepth: '',
      fiveDepth: '',
    },
    title: '테스트용',
    tprice: 150000,
  },
  {
    articleId: '3',
    image: 'image',
    category: {
      cid: '1325153',
      oneDepth: '',
      twoDepth: '',
      threeDepth: '',
      fourDepth: '',
      fiveDepth: '',
    },
    title: '테스트용',
    tprice: 150000,
  },
  {
    articleId: '4',
    image: 'image',
    category: {
      cid: '1325153',
      oneDepth: '',
      twoDepth: '',
      threeDepth: '',
      fourDepth: '',
      fiveDepth: '',
    },
    title: '테스트용',
    tprice: 150000,
  },
  {
    articleId: '5',
    image: 'image',
    category: {
      cid: '1325153',
      oneDepth: '',
      twoDepth: '',
      threeDepth: '',
      fourDepth: '',
      fiveDepth: '',
    },
    title: '테스트용',
    tprice: 150000,
  },
  {
    articleId: '6',
    image: 'image',
    category: {
      cid: '1325153',
      oneDepth: '',
      twoDepth: '',
      threeDepth: '',
      fourDepth: '',
      fiveDepth: '',
    },
    title: '테스트용',
    tprice: 150000,
  },
  {
    articleId: '7',
    image: 'image',
    category: {
      cid: '1325153',
      oneDepth: '',
      twoDepth: '',
      threeDepth: '',
      fourDepth: '',
      fiveDepth: '',
    },
    title: '테스트용',
    tprice: 150000,
  },
  {
    articleId: '8',
    image: 'image',
    category: {
      cid: '1325153',
      oneDepth: '',
      twoDepth: '',
      threeDepth: '',
      fourDepth: '',
      fiveDepth: '',
    },
    title: '테스트용',
    tprice: 150000,
  },
  {
    articleId: '9',
    image: 'image',
    category: {
      cid: '1325153',
      oneDepth: '',
      twoDepth: '',
      threeDepth: '',
      fourDepth: '',
      fiveDepth: '',
    },
    title: '테스트용',
    tprice: 150000,
  },
  {
    articleId: '10',
    image: 'image',
    category: {
      cid: '1325153',
      oneDepth: '',
      twoDepth: '',
      threeDepth: '',
      fourDepth: '',
      fiveDepth: '',
    },
    title: '테스트용',
    tprice: 150000,
  },
];

export default dummyMyArticleList;
